### ISSUE TITLE
Errors in script

### ISSUE THREAD

**Issue by vitriolvm** [CPVprogrammer/update-synology-index#7]
Hi there,
thanks for your work! I'm not yet managed to run the script because it gives two errors:
* if in config file I set up a non-recursive path (basically because I'm not sure what 'recursive' means) the scrip ends abruptly with: ``find: unknown predicate `-maxdepth 1'``
* if then I set up in config file that same path as recursive, then the `` `-maxdepth 1'`` error doesn't show; instead the script ends with the error: ``find: unknown predicate `-mmin -240'``

I'm new at Linux scripts so I'm not sure what can I do to fix this, anyway the first apostrophe (`` ` ``)  before `-mmin` and `-maxdepth` looks weird and different from the last one (`` ' ``). Could be a problem related to character encoding?

Thanks!

**Comment by CPVprogrammer** [comment]
Hi, if you have a directory and subdirectories then in recursive mode the script will process all of them.
In no recursive mode the script only process parent directory.

example:
#recursive will treat all if you use "/video" por path
/video
/video/tv shows
/video/music videos

#non recursive only this path if you use "/video/films" por path
/video/films


Linux commands use ( ` ) and ( ' ) to show errors. That is ok.

You have found a bug after script last change.
The bug is with command find that is not using parameters.

Now is working again
Thanks.

PD: if psql say that you dont have permissions, then execute the script like root.

**Comment by vitriolvm** [comment]
@CPVprogrammer, thank you for the explanations and for the fix: it now works perfectly well. Your script is very useful, thanks again for your work.
Just one last question: why I don't see able to make the script creating it's own log file? I set it up with `/volume1/video/New movies/` on the eighth row of the config file: I see the logging in the console as the script add all the movies but no log file is created. What am I doing wrong?

Thanks once again!

**Comment by CPVprogrammer** [comment]
Thanks for your kind words.
what you comment about log file is a little bug, but now it works
but now always must end with / if you only use a path and not a path/file
Thanks for find those bugs.
